### ISSUE TITLE
TODO LIST

### ISSUE THREAD

**Issue by Erctrn** [jeffuong/Axolotl#13]
- [ ] Add plugin feature
- [ ] Add status bar that shows current document details like line count, etc
- [ ] Add changeable themes/styles
- [X] Add file explorer _(reminder to go back and finish implementing new file switching whenever possible)_
- [ ] Add a console output
- [ ] Add settings or preferences to hide/show certain elements of the text editor 
- [X] Add syntax highlighting
- [ ] Add way to save/restore session
- [ ] Add a stay on top button
- [X] Fix imgs file naming
- [X] Fix tab key sizes
- [ ] Organize files into folders
- [ ] Text formatting options: let the user decide if tab = 2 or 4 spaces
- [X] Project name change and update files that still use old name
- [X] Periodically update readme images _(last update January 31, 2019)_
- [X] Update installer as new implementations come _(last update May 30, 2019)_
- [ ] Make icons more simplistic, for a better look
- [ ] Set up unit tests
- [ ] Put headers in a separate includes folder

_Settle on using either tabs, 2 space, or 4 space indentation.  The inconsistency is making the code look disjointed when reading it from Github._

**Comment by Erctrn** [comment]
Demo for readme.
![demo](https://user-images.githubusercontent.com/25240780/52088241-381ca400-2560-11e9-9e62-98f9d2b570f1.gif)

**Comment by Erctrn** [comment]
Updated demo _June 5, 2019_.
![demov2](https://user-images.githubusercontent.com/25240780/59009810-f2106f00-87e3-11e9-8d7d-106c6c87e01c.gif)
